name: Lint, Format, Build, Push & Deploy

on:
    push:
        branches: [main]
    pull_request:
        branches:
            - "**"

jobs:
    ci-check:
        name: Lint, Format, Build
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 24

            - uses: pnpm/action-setup@v3
              with:
                  version: 10

            - name: Install dependencies
              run: pnpm install

            - name: Run Ci fix
              run: pnpm ci:fix

            - name: Build Project
              run: pnpm build

    build-and-push:
        name: Build and Push Docker Image
        runs-on: ubuntu-latest
        needs: ci-check
        if: github.ref == 'refs/heads/main'

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Check required secrets
                uses: actions/github-script@v6
                with:
                    script: |
                        const secrets = {
                            DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }},
                            DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }},
                            PACKAGE_NAME: ${{ secrets.PACKAGE_NAME }},
                       }
                        const missingSecrets = Object.entries(secrets).filter(([key, value]) => {
                            if (value.length === 0) {
                                core.error(`Secret "${key}" is not set`);
                                return true;
                            }
                            core.info(`✅ "${key}" is set`);
                            return false;
                        });
                        if (missingSecrets.length > 0) {
                            core.setFailed(`❌ At least one required secret is not set in the repository. \n` +
                                `Name of the required secret: ${missingSecrets}`);
                        }

            - name: Log in to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Build and Push Docker image
              uses: docker/build-push-action@v5
              with:
                  context: .
                  push: true
                  tags: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.PACKAGE_NAME }}:latest

    deploy:
        name: Deploy
        runs-on: ubuntu-latest
        needs: build-and-push
        if: github.ref == 'refs/heads/main'

        steps:
            - uses: actions/checkout@v4

            - name: Check required secrets
                uses: actions/github-script@v6
                with:
                    script: |
                        const secrets = {
                            VPS_HOST: ${{ secrets.VPS_HOST }},
                            VPS_USER: ${{ secrets.VPS_USER }},
                            VPS_SSH_PRIVATE_KEY: ${{ secrets.VPS_SSH_PRIVATE_KEY }},
                            PORT: ${{ secrets.PORT }}
                        }
                        const missingSecrets = Object.entries(secrets).filter(([key, value]) => {
                            if (value.length === 0) {
                                core.error(`Secret "${key}" is not set`);
                                return true;
                            }
                            core.info(`✅ "${key}" is set`);
                            return false;
                        });
                        if (missingSecrets.length > 0) {
                            core.setFailed(`❌ At least one required secret is not set in the repository. \n` +
                                `Name of the required secret: ${missingSecrets}`);
                        }



            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Copy Compose File
              uses: appleboy/scp-action@v0.1.7
              with:
                  host: ${{ secrets.VPS_HOST }}
                  username: ${{ secrets.VPS_USER }}
                  key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
                  source: "docker-compose.yaml"
                  target: "~/${{ secrets.PACKAGE_NAME }}"

            - name: Copy Caddy File
              uses: appleboy/scp-action@v0.1.7
              with:
                  host: ${{ secrets.VPS_HOST }}
                  username: ${{ secrets.VPS_USER }}
                  key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
                  source: "Caddyfile"
                  target: "~/${{ secrets.PACKAGE_NAME }}"

            - name: Deploy via SSH
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: ${{ secrets.VPS_HOST }}
                  username: ${{ secrets.VPS_USER }}
                  key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
                  script: |
                      cd ~/${{ secrets.PACKAGE_NAME }}
                      # Pull the latest images
                      docker compose --profile prod pull

                      # Stop and remove existing containers safely
                      docker compose --profile prod down --remove-orphans

                      # Start containers in detached mode
                      docker compose --profile prod up -d

                      # Prune unused Docker objects (optional, cleans disk)
                      docker system prune -f
            - name: Restart Caddy
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: ${{ secrets.VPS_HOST }}
                  username: ${{ secrets.VPS_USER }}
                  key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
                  script: |
                      cd ~/${{ secrets.PACKAGE_NAME }}
                      docker compose --profile prod restart caddy
            - name: Test Deployment
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: ${{ secrets.VPS_HOST }}
                  username: ${{ secrets.VPS_USER }}
                  key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
                  script: |
                      cd ~/${{ secrets.PACKAGE_NAME }}
                      curl -s http://localhost:${{ secrets.PORT }}/api/health | grep ${{ secrets.PACKAGE_NAME }}
                      # if grep returns nothing then the deployment was failed
